Fix Braintrust update_span() API call
- Changed from braintrust.update_span() to span.update() method
- Added required 'exported' parameter to span.update() calls
- Fixes TypeError: update_span() missing 1 required positional argument: 'exported'